# Stellar SEP-1 & SEP-31 configuration
# .well-known/stellar.toml

NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
DIRECT_PAYMENT_SERVER="https://bridge.uctalent.dev/sep31"
WEB_AUTH_ENDPOINT="https://bridge.uctalent.dev/auth"

[[CURRENCIES]]
code="USDC"
issuer="GBBD47IF6LWK7P7MDEVSCZA7CFYGLVOLO25E34XDBIEU7E5XPIUBIVGF"
status="live"
is_asset_anchored=true
desc="USD Coin on Stellar Testnet"

[[CURRENCIES]]
code="VND"
desc="Vietnamese Dong (Off-chain representation)"
is_asset_anchored=false
