items:
  - id: stellar:USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN
    distribution_account: GBLSAHONJRODSFTLOV225NZR4LHICH63RIFQTQN37L5CRTR2IMQ5UEK7
    significant_decimals: 7
    sep31:
      enabled: true
      receive:
        methods:
          - "stellar"
      sep12:
        sender:
          types:
            sep31-sender:
              description: "Enterprise client sending payment"
        receiver:
          types:
            sep31-receiver:
              description: "Freelancer receiving VND disbursement"
    sep38:
      enabled: true
      exchangeable_assets:
        - iso4217:VND

  - id: iso4217:VND
    significant_decimals: 0
    quotes_supported: true
    quotes_required: false
    buy_delivery_methods:
      - name: NAPAS
        description: "Transfer VND to Vietnamese bank account"
    sep31:
      enabled: true
      receive:
        methods:
          - "bank_account"
    sep38:
      enabled: true
      exchangeable_assets:
        - stellar:USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN
