#!/usr/bin/env python3
"""
render-env.py — Render .env file for uc-stellar (Cross-Border)
===============================================================
Usage (called from Cloud Build step):
  python3 scripts/render-env.py \
    NODE_ENV=production \
    PORT=8081 \
    ...

Secrets are injected via SECRET_JSON environment variable
(a JSON string fetched from GCP Secret Manager).

Output: writes .env to current working directory.
"""

import json
import os
import sys

# Keys required in SECRET_JSON for a production-like deploy.
# SLACK_ALERT_WEBHOOK is optional and intentionally omitted.
REQUIRED_SECRET_KEYS = [
    "POSTGRES_USER",
    "POSTGRES_PASSWORD",
    "USDC_ISSUER",
    "ENCRYPTION_SECRET",
    "JWT_SECRET",
]


def render_non_secret_env(args: list[str]) -> dict[str, str]:
    """Parse KEY=VALUE pairs from CLI arguments."""
    env_vars = {}
    for arg in args:
        if "=" in arg:
            key, _, value = arg.partition("=")
            env_vars[key.strip()] = value.strip()
        else:
            print(f"[WARN] Skipping malformed arg: {arg}", file=sys.stderr)
    return env_vars


def render_secret_env(secret_json_str: str) -> dict[str, str]:
    """
    Parse secrets from GCP Secret Manager JSON blob.
    Handles nested dict/list values by serializing them as compact JSON strings.
    """
    try:
        data = json.loads(secret_json_str)
    except json.JSONDecodeError as e:
        print(f"[ERROR] Failed to parse SECRET_JSON: {e}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(data, dict):
        print("[ERROR] SECRET_JSON must be a JSON object of key/value pairs.", file=sys.stderr)
        sys.exit(1)

    secret_vars = {}
    for key, value in data.items():
        if isinstance(value, (dict, list)):
            value = json.dumps(value, separators=(",", ":"), ensure_ascii=False)
        secret_vars[str(key)] = str(value)

    return secret_vars


def validate_required_secrets(secrets: dict[str, str]) -> None:
    """Fail fast if required secret keys are missing or empty."""
    extra = os.environ.get("REQUIRED_SECRET_KEYS", "").strip()
    required = list(REQUIRED_SECRET_KEYS)
    if extra:
        required.extend([k.strip() for k in extra.split(",") if k.strip()])

    missing = [k for k in required if not secrets.get(k)]
    if missing:
        print(
            f"[ERROR] SECRET_JSON missing required keys: {', '.join(missing)}",
            file=sys.stderr,
        )
        sys.exit(1)

    for key in ("ENCRYPTION_SECRET", "JWT_SECRET"):
        if key in secrets and len(secrets[key]) < 32:
            print(
                f"[ERROR] {key} must be at least 32 characters (got {len(secrets[key])}).",
                file=sys.stderr,
            )
            sys.exit(1)


def write_env_file(non_secrets: dict, secrets: dict, output_path: str = ".env") -> None:
    """Write merged env vars to output file. Secrets override non-secrets."""
    merged = {**non_secrets, **secrets}

    lines = []
    lines.append("# Auto-generated by scripts/render-env.py — DO NOT EDIT MANUALLY\n")
    lines.append("# Non-secret vars come from Cloud Build substitutions.\n")
    lines.append("# Secret vars come from GCP Secret Manager.\n")
    lines.append("\n")

    lines.append("# ===== NON-SECRET (Cloud Build substitutions) =====\n")
    for key, value in non_secrets.items():
        if key not in secrets:
            lines.append(f"{key}={value}\n")

    lines.append("\n")
    lines.append("# ===== SECRETS (from GCP Secret Manager) =====\n")
    for key, value in secrets.items():
        lines.append(f"{key}={value}\n")

    with open(output_path, "w") as f:
        f.writelines(lines)

    print(f"[OK] .env written to {output_path} ({len(merged)} variables)", file=sys.stderr)


def main() -> None:
    args = sys.argv[1:]

    if not args:
        print("[ERROR] No KEY=VALUE pairs provided as arguments.", file=sys.stderr)
        sys.exit(1)

    non_secrets = render_non_secret_env(args)
    print(f"[INFO] Non-secret vars: {len(non_secrets)}", file=sys.stderr)

    secret_json_str = os.environ.get("SECRET_JSON", "").strip()
    if not secret_json_str:
        print(
            "[ERROR] SECRET_JSON not set — refusing to write .env without secrets.",
            file=sys.stderr,
        )
        sys.exit(1)

    secrets = render_secret_env(secret_json_str)
    print(f"[INFO] Secret vars: {len(secrets)}", file=sys.stderr)
    validate_required_secrets(secrets)

    write_env_file(non_secrets, secrets)


if __name__ == "__main__":
    main()
